/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MapRouteImport } from './routes/map'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizerIndexRouteImport } from './routes/organizer/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PostIdRouteImport } from './routes/post.$id'
import { Route as OrganizerNewRouteImport } from './routes/organizer/new'
import { Route as OrganizerAdsRouteImport } from './routes/organizer/ads'
import { Route as EventSlugRouteImport } from './routes/event.$slug'

const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerIndexRoute = OrganizerIndexRouteImport.update({
  id: '/organizer/',
  path: '/organizer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerNewRoute = OrganizerNewRouteImport.update({
  id: '/organizer/new',
  path: '/organizer/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerAdsRoute = OrganizerAdsRouteImport.update({
  id: '/organizer/ads',
  path: '/organizer/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSlugRoute = EventSlugRouteImport.update({
  id: '/event/$slug',
  path: '/event/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/event/$slug': typeof EventSlugRoute
  '/organizer/ads': typeof OrganizerAdsRoute
  '/organizer/new': typeof OrganizerNewRoute
  '/post/$id': typeof PostIdRoute
  '/admin/': typeof AdminIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/event/$slug': typeof EventSlugRoute
  '/organizer/ads': typeof OrganizerAdsRoute
  '/organizer/new': typeof OrganizerNewRoute
  '/post/$id': typeof PostIdRoute
  '/admin': typeof AdminIndexRoute
  '/organizer': typeof OrganizerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/event/$slug': typeof EventSlugRoute
  '/organizer/ads': typeof OrganizerAdsRoute
  '/organizer/new': typeof OrganizerNewRoute
  '/post/$id': typeof PostIdRoute
  '/admin/': typeof AdminIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/auth'
    | '/favorites'
    | '/map'
    | '/profile'
    | '/reset-password'
    | '/sitemap.xml'
    | '/social'
    | '/event/$slug'
    | '/organizer/ads'
    | '/organizer/new'
    | '/post/$id'
    | '/admin/'
    | '/organizer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/auth'
    | '/favorites'
    | '/map'
    | '/profile'
    | '/reset-password'
    | '/sitemap.xml'
    | '/social'
    | '/event/$slug'
    | '/organizer/ads'
    | '/organizer/new'
    | '/post/$id'
    | '/admin'
    | '/organizer'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/auth'
    | '/favorites'
    | '/map'
    | '/profile'
    | '/reset-password'
    | '/sitemap.xml'
    | '/social'
    | '/event/$slug'
    | '/organizer/ads'
    | '/organizer/new'
    | '/post/$id'
    | '/admin/'
    | '/organizer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AuthRoute: typeof AuthRoute
  FavoritesRoute: typeof FavoritesRoute
  MapRoute: typeof MapRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SocialRoute: typeof SocialRoute
  EventSlugRoute: typeof EventSlugRoute
  OrganizerAdsRoute: typeof OrganizerAdsRoute
  OrganizerNewRoute: typeof OrganizerNewRoute
  PostIdRoute: typeof PostIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OrganizerIndexRoute: typeof OrganizerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/': {
      id: '/organizer/'
      path: '/organizer'
      fullPath: '/organizer/'
      preLoaderRoute: typeof OrganizerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/new': {
      id: '/organizer/new'
      path: '/organizer/new'
      fullPath: '/organizer/new'
      preLoaderRoute: typeof OrganizerNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/ads': {
      id: '/organizer/ads'
      path: '/organizer/ads'
      fullPath: '/organizer/ads'
      preLoaderRoute: typeof OrganizerAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$slug': {
      id: '/event/$slug'
      path: '/event/$slug'
      fullPath: '/event/$slug'
      preLoaderRoute: typeof EventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AuthRoute: AuthRoute,
  FavoritesRoute: FavoritesRoute,
  MapRoute: MapRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SocialRoute: SocialRoute,
  EventSlugRoute: EventSlugRoute,
  OrganizerAdsRoute: OrganizerAdsRoute,
  OrganizerNewRoute: OrganizerNewRoute,
  PostIdRoute: PostIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  OrganizerIndexRoute: OrganizerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
