// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import {
  isAllowedSupabaseReadProxyRequest,
  SUPABASE_READ_PROXY_ROUTE,
  SUPABASE_READ_PROXY_TARGET_HEADER,
} from "@/lib/supabase-read-proxy";

const SUPABASE_DIRECT_TIMEOUT_MS = 4_000;
const SUPABASE_DIRECT_CIRCUIT_MS = 60_000;
const PROXY_FORWARDED_HEADERS = [
  "accept",
  "authorization",
  "content-type",
  "prefer",
  "range",
  "x-client-info",
] as const;

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

type SupabaseFetchOptions = {
  fetcher?: typeof fetch;
  proxyOrigin?: string | null;
  now?: () => number;
  directTimeoutMs?: number;
  circuitMs?: number;
};

async function createProxyRequest(request: Request, proxyOrigin: string): Promise<Request> {
  const target = new URL(request.url);
  const headers = new Headers();
  for (const name of PROXY_FORWARDED_HEADERS) {
    const value = request.headers.get(name);
    if (value) headers.set(name, value);
  }
  headers.set(SUPABASE_READ_PROXY_TARGET_HEADER, `${target.pathname}${target.search}`);

  return new Request(new URL(SUPABASE_READ_PROXY_ROUTE, proxyOrigin), {
    method: request.method,
    headers,
    body: ["GET", "HEAD"].includes(request.method)
      ? undefined
      : await request.clone().arrayBuffer(),
    signal: request.signal,
  });
}

export function createSupabaseFetch(
  supabaseKey: string,
  {
    fetcher = fetch,
    proxyOrigin = typeof window !== "undefined" ? window.location.origin : null,
    now = Date.now,
    directTimeoutMs = SUPABASE_DIRECT_TIMEOUT_MS,
    circuitMs = SUPABASE_DIRECT_CIRCUIT_MS,
  }: SupabaseFetchOptions = {},
): typeof fetch {
  let directUnavailableUntil = 0;

  return async (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    const request = new Request(input, { ...init, headers });
    const target = new URL(request.url);
    const canUseReadProxy = Boolean(
      proxyOrigin && isAllowedSupabaseReadProxyRequest(request.method, target.pathname),
    );
    if (!canUseReadProxy) return fetcher(request);

    if (now() < directUnavailableUntil) {
      return fetcher(await createProxyRequest(request, proxyOrigin!));
    }

    const directController = new AbortController();
    const forwardAbort = () => directController.abort(request.signal.reason);
    if (request.signal.aborted) forwardAbort();
    else request.signal.addEventListener("abort", forwardAbort, { once: true });
    const timeout = setTimeout(
      () =>
        directController.abort(
          new DOMException("Supabase direct request timed out", "TimeoutError"),
        ),
      Math.max(1, directTimeoutMs),
    );

    try {
      return await fetcher(new Request(request.clone(), { signal: directController.signal }));
    } catch (error) {
      if (request.signal.aborted) throw error;
      directUnavailableUntil = now() + Math.max(0, circuitMs);
      return fetcher(await createProxyRequest(request, proxyOrigin!));
    } finally {
      clearTimeout(timeout);
      request.signal.removeEventListener("abort", forwardAbort);
    }
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
